version: 0.2

phases:
  install:
    commands:
  build:
    commands:
      - docker login -u andreas.eliasson -p yacloud1 https://git.systementor.se
      - docker build -t git.systementor.se/andreas.eliasson/urbanlegends-flasksite .
      - docker push git.systementor.se/andreas.eliasson/urbanlegends-flasksite